Dev
husush23/Capstone--3 pull request #12
Opened 2023-07-05 18:44 UTC by husush23

2023-07-05 20:03 UTC, mikethreels requested changes
Hi Hussein, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- good job making the project work.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-05 20:03 UTC, mikethreels commented on README.md
> +
- [ ] according to the requirements you should deploy the application using Render, Netlify or GitHub Pages and a link to the deployed project should be present in the README.
- [ ] you should have recorded a video presenting the features of the project, please take the below requirements into consideration when creating the video:
  - The maximum length of the video is 5 minutes.
  - The video should contain a clear and objective description of the project in professional English. The topic and purpose of the project are made clear.
  - The video should contain a demo of the project, highlighting all the project features.
  - The video should contain a highlight about a piece of the code you find interesting or are proud of making.

2023-07-05 20:03 UTC, mikethreels commented on README.md
> +
- [ ] according to the requirements the README should contain an "Acknowledgements" section or similar that gives appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2023-07-05 20:03 UTC, mikethreels commented on README.md
> +This project is [MIT](./MIT.md) licensed.
- [ ] The link to the license is not working as expected please make sure it is working as presented in the Microverse template.

2023-07-05 20:03 UTC, mikethreels commented on src/App.js
> +          <Route path="/" element={<Currencies />} />
- [x] According to the requirements the Layout should be the same as the example which includes composition and space between elements. Have a look at the below examples and please make sure to make your project more similar to the original:
original:
![afbeelding](https://github.com/husush23/Capstone--3/assets/39240820/76b2748e-d838-449a-a666-94e3a32079fb)
your project:
![afbeelding](https://github.com/husush23/Capstone--3/assets/39240820/e93cc020-faf9-4929-9168-78f66f7daee9)

2023-07-06 07:01 UTC, husush23 commented on src/App.js
> +          <Route path="/" element={<Currencies />} />
I removed the margin between the  items and this the look, it looks the same the difference is the color and search box.
![Screenshot 2023-07-06 095935](https://github.com/husush23/Capstone--3/assets/114058667/1ebb3a87-d11c-4ec6-b67c-572f81e08818)

2023-07-06 09:10 UTC, VICTOR-CHUKWU requested changes
Hi @husush23 , 
## STATUS: CHANGES REQUIRED :recycle: 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-07-06 09:10 UTC, VICTOR-CHUKWU commented on src/App.js
> +          <Route path="/" element={<Currencies />} />
- [ ] You did a good job implementing the changes required but the background of the card is not looking like the design on mobile, know that the card's background colour is supposed to be interchanged between cards. you can achieve this by giving all odd-numbered cards a light background and all even-numbered cards a darker background
in your design :point_down: 
![Screenshot from 2023-07-06 09-59-24](https://github.com/husush23/Capstone--3/assets/66097371/1c9a0b93-c296-4fef-97c3-1296cd413bc0)
given design :point_down: 
![Screenshot from 2023-04-28 11-04-25](https://github.com/husush23/Capstone--3/assets/66097371/18a8100f-9e37-4ae5-917d-237111571d77)

2023-07-06 09:14 UTC, husush23 commented on src/App.js
> +          <Route path="/" element={<Currencies />} />
@VICTOR-CHUKWU You see that I gave the color every odd card a different color and also every even too, what is the other things you are saying please be clear

2023-07-06 09:23 UTC, VICTOR-CHUKWU commented on src/App.js
> +          <Route path="/" element={<Currencies />} />
so what is happening in mobile is that all odd cards are under each other so you can use this selector `*:nth-child(4n + 1)` to make the background diff

2023-07-06 09:23 UTC, VICTOR-CHUKWU commented on src/App.js
> +          <Route path="/" element={<Currencies />} />
i hope that works

2023-07-06 09:59 UTC, Ghiftee approved these changes
## STATUS: APPROVED ♻️♻️
Hi @husush23, 

To highlight 👍🏽 
✔️ Card colours are alternating
✔️ App is deployed
✔️ Video presentation is made

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

![](https://user-images.githubusercontent.com/71140133/250156478-7da8ef4f-9230-4f28-951f-b0ea618e460d.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-06 10:13 UTC, merged